language: rust
dist: bionic

matrix:
  include:
  - os: linux
    rust: stable
    env: BUILD_MODE=build
  - os: linux
    rust: stable
    env: BUILD_MODE=integration
  - os: osx
    rust: stable
    env: BUILD_MODE=build

before_install:
- ci/dependencies.sh
script:
- ci/run.sh
