language: rust

matrix:
  include:
  - os: linux
    rust: stable
    env: BUILD_MODE=build
  - os: linux
    rust: stable
    env: BUILD_MODE=integration

before_install:
- sudo ci/dependencies.sh
script:
- ci/run.sh
