[package]
name = "badtouch"
version = "0.1.0"
description = "Scriptable network authentication cracker"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/badtouch"
categories = ["command-line-utilities"]
readme = "README.md"

[badges]
travis-ci = { repository = "kpcyrd/badtouch" }

[dependencies]
hlua = "0.4"
pbr = "1.0"
# pbr = { path = "../pb" }
threadpool = "1.7"
structopt = "0.2"
error-chain = "0.11"
libc = "0.2"
